import "server-only";
import { getCurrentRanchContext } from "@/features/ranch/services/ranch-context-service";
import { createClient } from "@/lib/supabase/server";
import type { Guest, GuestStatus, GuestWithReservation } from "../types";
export type GuestInput = { reservation_id: string | null; first_name: string; last_name: string; nickname: string | null; age: number | null; phone: string | null; emergency_contact_name: string | null; emergency_contact_phone: string | null; arrival_date: string | null; departure_date: string | null; riding_experience: string | null; height_inches: number | null; weight_lbs: number | null; medical_notes: string | null; special_notes: string | null; status: GuestStatus };
async function requireGuestPrepManager() { const context = await getCurrentRanchContext(); if (!context || !["ranch_administrator", "head_wrangler"].includes(context.role)) throw new Error("Guest prep access is required."); return context; }
export async function listGuests(): Promise<GuestWithReservation[]> { const { ranchId } = await requireGuestPrepManager(); const supabase = await createClient(); const { data, error } = await supabase.from("guests").select("*,reservation:reservations(reservation_name,primary_contact_name)").eq("ranch_id", ranchId).order("status").order("last_name"); if (error) throw error; return data as GuestWithReservation[]; }
export async function getGuest(id: string): Promise<Guest | null> { const { ranchId } = await requireGuestPrepManager(); const supabase = await createClient(); const { data, error } = await supabase.from("guests").select("*").eq("ranch_id", ranchId).eq("id", id).maybeSingle(); if (error) throw error; return data as Guest | null; }
export async function listGuestsForReservation(reservationId: string): Promise<Guest[]> { const { ranchId } = await requireGuestPrepManager(); const supabase = await createClient(); const { data, error } = await supabase.from("guests").select("*").eq("ranch_id", ranchId).eq("reservation_id", reservationId).order("last_name"); if (error) throw error; return data as Guest[]; }
export async function createGuest(input: GuestInput) { const { ranchId } = await requireGuestPrepManager(); const supabase = await createClient(); return supabase.from("guests").insert({ ...input, ranch_id: ranchId }); }
export async function updateGuest(id: string, input: GuestInput) { const { ranchId } = await requireGuestPrepManager(); const supabase = await createClient(); return supabase.from("guests").update(input).eq("ranch_id", ranchId).eq("id", id); }
export async function archiveGuest(id: string) { const { ranchId } = await requireGuestPrepManager(); const supabase = await createClient(); return supabase.from("guests").update({ status: "archived" }).eq("ranch_id", ranchId).eq("id", id); }
export async function removeGuestFromReservation(id: string, reservationId: string) { const { ranchId } = await requireGuestPrepManager(); const supabase = await createClient(); return supabase.from("guests").update({ reservation_id: null }).eq("ranch_id", ranchId).eq("reservation_id", reservationId).eq("id", id); }
