"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { archiveGuest, createGuest, removeGuestFromReservation, updateGuest, type GuestInput } from "./guest-service";
import type { GuestFormState, GuestStatus } from "../types";
function parse(formData: FormData): { input?: GuestInput; state?: GuestFormState } { const value = (key: string) => String(formData.get(key) ?? "").trim(); const firstName = value("firstName"); const lastName = value("lastName"); const rawAge = value("age"); const rawHeight = value("height"); const rawWeight = value("weight"); const age = rawAge ? Number(rawAge) : null; const height = rawHeight ? Number(rawHeight) : null; const weight = rawWeight ? Number(rawWeight) : null; const arrival = value("arrivalDate"); const departure = value("departureDate"); const fieldErrors: GuestFormState["fieldErrors"] = {}; if (!firstName) fieldErrors.firstName = "First name is required."; if (!lastName) fieldErrors.lastName = "Last name is required."; if (age !== null && (!Number.isInteger(age) || age < 0 || age > 125)) fieldErrors.age = "Enter a valid age."; if (height !== null && (Number.isNaN(height) || height <= 0)) fieldErrors.height = "Enter height in inches."; if (weight !== null && (!Number.isInteger(weight) || weight <= 0)) fieldErrors.weight = "Enter a positive whole number."; if (arrival && departure && departure < arrival) fieldErrors.dates = "Departure must be on or after arrival."; if (Object.keys(fieldErrors).length) return { state: { status: "error", fieldErrors } }; return { input: { reservation_id: value("reservationId") || null, first_name: firstName, last_name: lastName, nickname: value("nickname") || null, age, phone: value("phone") || null, emergency_contact_name: value("emergencyName") || null, emergency_contact_phone: value("emergencyPhone") || null, arrival_date: arrival || null, departure_date: departure || null, riding_experience: value("ridingExperience") || null, height_inches: height, weight_lbs: weight, medical_notes: value("medicalNotes") || null, special_notes: value("specialNotes") || null, status: (value("status") || "reserved") as GuestStatus } }; }
export async function createGuestAction(_state: GuestFormState, formData: FormData): Promise<GuestFormState> { const parsed = parse(formData); if (parsed.state) return parsed.state; const { error } = await createGuest(parsed.input!); if (error) return { status: "error", message: error.message }; revalidatePath("/dashboard"); redirect("/dashboard/guests"); }
export async function updateGuestAction(id: string, _state: GuestFormState, formData: FormData): Promise<GuestFormState> { const parsed = parse(formData); if (parsed.state) return parsed.state; const { error } = await updateGuest(id, parsed.input!); if (error) return { status: "error", message: error.message }; revalidatePath("/dashboard"); redirect("/dashboard/guests"); }
export async function archiveGuestAction(id: string) { const { error } = await archiveGuest(id); if (error) throw new Error("Unable to archive guest."); revalidatePath("/dashboard/guests"); revalidatePath("/dashboard"); }
export async function removeGuestFromReservationAction(id: string, reservationId: string) { const { error } = await removeGuestFromReservation(id, reservationId); if (error) throw new Error("Unable to remove guest from reservation."); revalidatePath(`/dashboard/reservations/${reservationId}/edit`); revalidatePath("/dashboard/guests"); }
