import "server-only";
import { getCurrentRanchContext } from "@/features/ranch/services/ranch-context-service";
import { createClient } from "@/lib/supabase/server";
import type { Guest, GuestStatus, GuestWithPrep } from "../types";
export type GuestInput = { reservation_id: string | null; first_name: string; last_name: string; nickname: string | null; age: number | null; phone: string | null; emergency_contact_name: string | null; emergency_contact_phone: string | null; arrival_date: string | null; departure_date: string | null; riding_experience: string | null; height_inches: number | null; weight_lbs: number | null; medical_notes: string | null; special_notes: string | null; status: GuestStatus };
async function requireGuestPrepManager() { const context = await getCurrentRanchContext(); if (!context || !["ranch_administrator", "head_wrangler"].includes(context.role)) throw new Error("Guest prep access is required."); return context; }
export async function listGuests(): Promise<GuestWithPrep[]> { const { ranchId } = await requireGuestPrepManager(); const supabase = await createClient(); const [guests, assignments] = await Promise.all([supabase.from("guests").select("*,reservation:reservations(reservation_name,primary_contact_name)").eq("ranch_id", ranchId).neq("status", "archived").order("status").order("last_name"), supabase.from("reservation_guest_assignments").select("guest_id,horse_id,saddle_id,horse:horses(name),saddle:saddles(name)").eq("ranch_id", ranchId)]); if (guests.error) throw guests.error; if (assignments.error) throw assignments.error; const byGuest = new Map((assignments.data as unknown as Array<{ guest_id: string; horse_id: string | null; saddle_id: string | null; horse: { name: string } | null; saddle: { name: string } | null }>).map((item) => [item.guest_id, item])); return (guests.data as GuestWithPrep[]).map((guest) => ({ ...guest, riding_assignment: byGuest.get(guest.id) ?? null })); }
export async function getGuest(id: string): Promise<Guest | null> { const { ranchId } = await requireGuestPrepManager(); const supabase = await createClient(); const { data, error } = await supabase.from("guests").select("*").eq("ranch_id", ranchId).eq("id", id).maybeSingle(); if (error) throw error; return data as Guest | null; }
export async function listGuestsForReservation(reservationId: string): Promise<Guest[]> { const { ranchId } = await requireGuestPrepManager(); const supabase = await createClient(); const { data, error } = await supabase.from("guests").select("*").eq("ranch_id", ranchId).eq("reservation_id", reservationId).order("last_name"); if (error) throw error; return data as Guest[]; }
export async function createGuest(input: GuestInput) { const { ranchId } = await requireGuestPrepManager(); const supabase = await createClient(); return supabase.from("guests").insert({ ...input, ranch_id: ranchId }); }
export async function updateGuest(id: string, input: GuestInput) { const { ranchId } = await requireGuestPrepManager(); const supabase = await createClient(); return supabase.from("guests").update(input).eq("ranch_id", ranchId).eq("id", id); }
export async function archiveGuest(id: string) { const { ranchId } = await requireGuestPrepManager(); const supabase = await createClient(); return supabase.from("guests").update({ status: "archived" }).eq("ranch_id", ranchId).eq("id", id); }
export async function removeGuestFromReservation(id: string, reservationId: string) { const { ranchId } = await requireGuestPrepManager(); const supabase = await createClient(); return supabase.from("guests").update({ reservation_id: null }).eq("ranch_id", ranchId).eq("reservation_id", reservationId).eq("id", id); }
