"use client";

import { useActionState } from "react";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { AuthMessage } from "@/features/authentication/components/auth-message";
import { SubmitButton } from "@/features/authentication/components/submit-button";
import { createActivityAction, updateActivityAction } from "../services/activity-actions";
import { initialActivityFormState, type Activity, type ActivityOption } from "../types";
type FieldProps = { label: string; name: string; error?: string; defaultValue?: string | null } & Omit<React.ComponentProps<typeof Input>, "defaultValue" | "name">;
export function ActivityForm({ activity, activityTypes, trails }: { activity?: Activity; activityTypes: ActivityOption[]; trails: ActivityOption[] }) { const action = activity ? updateActivityAction.bind(null, activity.id) : createActivityAction; const [state, formAction] = useActionState(action, initialActivityFormState); return <form action={formAction} className="space-y-5 p-6"><AuthMessage state={state} /><Field label="Activity name (optional)" name="name" defaultValue={activity?.name} placeholder="Morning Ride" /><div className="grid gap-5 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="activityType">Activity type</Label><select id="activityType" name="activityType" defaultValue={activity?.activity_type_id ?? ""} className="h-10 w-full rounded-lg border bg-background px-3 text-sm" required><option value="">Choose a type</option>{activityTypes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>{state.fieldErrors?.activityType && <p className="text-sm text-destructive">{state.fieldErrors.activityType}</p>}</div><div className="space-y-2"><Label htmlFor="trail">Trail (optional)</Label><select id="trail" name="trail" defaultValue={activity?.trail_id ?? ""} className="h-10 w-full rounded-lg border bg-background px-3 text-sm"><option value="">No trail</option>{trails.map((trail) => <option key={trail.id} value={trail.id}>{trail.name}</option>)}</select></div></div><div className="grid gap-5 sm:grid-cols-3"><Field label="Date" name="date" type="date" required defaultValue={activity?.activity_date} error={state.fieldErrors?.date} /><Field label="Start time" name="startTime" type="time" defaultValue={activity?.start_time?.slice(0, 5)} error={state.fieldErrors?.times} /><Field label="End time" name="endTime" type="time" defaultValue={activity?.end_time?.slice(0, 5)} error={state.fieldErrors?.times} /></div><div className="grid gap-5 sm:grid-cols-2"><Field label="Capacity" name="capacity" type="number" min={1} step={1} defaultValue={activity?.capacity?.toString()} error={state.fieldErrors?.capacity} /><div className="space-y-2"><Label htmlFor="status">Status</Label><select id="status" name="status" defaultValue={activity?.status ?? "draft"} className="h-10 w-full rounded-lg border bg-background px-3 text-sm"><option value="draft">Draft</option><option value="ready">Ready</option><option value="in_progress">In Progress</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></div></div><div className="space-y-2"><Label htmlFor="notes">Notes</Label><Textarea id="notes" name="notes" defaultValue={activity?.notes ?? ""} /></div>{!activityTypes.length && <p className="rounded-lg bg-primary/10 p-3 text-sm text-primary">Create an active Activity Type before scheduling an activity.</p>}<div className="pt-2 sm:w-48"><SubmitButton>{activity ? "Save changes" : "Schedule activity"}</SubmitButton></div></form>; }
function Field({ label, name, error, defaultValue, ...props }: FieldProps) { return <div className="space-y-2"><Label htmlFor={name}>{label}</Label><Input id={name} name={name} defaultValue={defaultValue ?? ""} aria-invalid={Boolean(error)} {...props} />{error && <p className="text-sm text-destructive">{error}</p>}</div>; }
