"use client";
import { useActionState } from "react";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { AuthMessage } from "@/features/authentication/components/auth-message";
import { SubmitButton } from "@/features/authentication/components/submit-button";
import { createTrailAction, updateTrailAction } from "../services/trail-actions";
import { initialTrailFormState, type Trail } from "../types";
export function TrailForm({ trail }: { trail?: Trail }) { const action = trail ? updateTrailAction.bind(null, trail.id) : createTrailAction; const [state, formAction] = useActionState(action, initialTrailFormState); return <form action={formAction} className="space-y-5 p-6"><AuthMessage state={state} /><div className="grid gap-5 sm:grid-cols-2"><Field label="Trail name" name="name" defaultValue={trail?.name} required error={state.fieldErrors?.name} /><div className="space-y-2"><Label htmlFor="difficulty">Difficulty</Label><select id="difficulty" name="difficulty" defaultValue={trail?.difficulty ?? ""} className="h-10 w-full rounded-lg border bg-background px-3 text-sm"><option value="">Not specified</option><option value="easy">Easy</option><option value="moderate">Moderate</option><option value="difficult">Difficult</option><option value="expert">Expert</option></select></div></div><div className="grid gap-5 sm:grid-cols-2"><Field label="Estimated duration (minutes)" name="duration" type="number" min={1} step={1} defaultValue={trail?.estimated_duration_minutes?.toString()} error={state.fieldErrors?.duration} /><div className="space-y-2"><Label htmlFor="active">Status</Label><select id="active" name="active" defaultValue={trail?.active === false ? "false" : "true"} className="h-10 w-full rounded-lg border bg-background px-3 text-sm"><option value="true">Active</option><option value="false">Archived</option></select></div></div><div className="space-y-2"><Label htmlFor="description">Description</Label><Textarea id="description" name="description" defaultValue={trail?.description ?? ""} /></div><div className="space-y-2"><Label htmlFor="notes">Internal notes</Label><Textarea id="notes" name="notes" defaultValue={trail?.notes ?? ""} /></div><div className="pt-2 sm:w-48"><SubmitButton>{trail ? "Save changes" : "Add trail"}</SubmitButton></div></form>; }
function Field({ label, name, error, defaultValue, ...props }: { label: string; name: string; error?: string; defaultValue?: string | null } & React.ComponentProps<typeof Input>) { return <div className="space-y-2"><Label htmlFor={name}>{label}</Label><Input id={name} name={name} defaultValue={defaultValue ?? ""} aria-invalid={Boolean(error)} {...props} />{error && <p className="text-sm text-destructive">{error}</p>}</div>; }
