"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { archiveTrail, createTrail, updateTrail, type TrailInput } from "./trail-service";
import type { TrailFormState } from "../types";
function parse(formData: FormData): { input?: TrailInput; state?: TrailFormState } { const value = (key: string) => String(formData.get(key) ?? "").trim(); const name = value("name"); const rawDuration = value("duration"); const duration = rawDuration ? Number(rawDuration) : null; const fieldErrors: TrailFormState["fieldErrors"] = {}; if (!name) fieldErrors.name = "Trail name is required."; if (duration !== null && (!Number.isInteger(duration) || duration <= 0)) fieldErrors.duration = "Enter positive whole minutes."; if (Object.keys(fieldErrors).length) return { state: { status: "error", fieldErrors } }; return { input: { name, difficulty: value("difficulty") || null, estimated_duration_minutes: duration, description: value("description") || null, notes: value("notes") || null, active: value("active") !== "false" } }; }
export async function createTrailAction(_state: TrailFormState, formData: FormData): Promise<TrailFormState> { const parsed = parse(formData); if (parsed.state) return parsed.state; const { error } = await createTrail(parsed.input!); if (error) return { status: "error", message: error.message }; revalidatePath("/dashboard"); redirect("/dashboard/trails"); }
export async function updateTrailAction(id: string, _state: TrailFormState, formData: FormData): Promise<TrailFormState> { const parsed = parse(formData); if (parsed.state) return parsed.state; const { error } = await updateTrail(id, parsed.input!); if (error) return { status: "error", message: error.message }; revalidatePath("/dashboard"); redirect("/dashboard/trails"); }
export async function archiveTrailAction(id: string) { const { error } = await archiveTrail(id); if (error) throw new Error("Unable to archive trail."); revalidatePath("/dashboard/trails"); revalidatePath("/dashboard"); }
