import { Archive, CalendarDays, Pencil } from "lucide-react";
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/features/dashboard/components/empty-state";
import { archiveReservationAction } from "../services/reservation-actions";
import type { Reservation } from "../types";
const formatDate = (date: string | null) => date ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" }).format(new Date(`${date}T00:00:00Z`)) : "Not set";
export function ReservationList({ reservations }: { reservations: Reservation[] }) { if (!reservations.length) return <EmptyState icon={CalendarDays} title="No reservations yet" description="Create a reservation to organize families, parties, retreats, or other guest groups." href="/dashboard/reservations/new" action="Add reservation" />; return <div className="grid gap-4 md:grid-cols-2">{reservations.map((reservation) => <div key={reservation.id} className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{reservation.reservation_name || reservation.primary_contact_name || "Unnamed reservation"}</h2><p className="mt-1 text-sm text-muted-foreground">{reservation.primary_contact_name || "No primary contact"}</p></div><Badge className={reservation.status === "archived" ? "" : "bg-primary/10 text-primary"}>{reservation.status.replace("_", " ")}</Badge></div><div className="mt-5 flex items-center gap-2 text-sm text-muted-foreground"><CalendarDays className="size-4" />{formatDate(reservation.arrival_date)} – {formatDate(reservation.departure_date)}</div><div className="mt-5 flex justify-end gap-1 border-t pt-3"><Button asChild variant="ghost" size="sm"><Link href={`/dashboard/reservations/${reservation.id}/edit`}><Pencil />Edit</Link></Button>{reservation.status !== "archived" && <form action={archiveReservationAction.bind(null, reservation.id)}><Button variant="ghost" size="sm"><Archive />Archive</Button></form>}</div></div>)}</div>; }
