import { Archive, Pencil, Users } from "lucide-react";
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/features/dashboard/components/empty-state";
import { archiveEmployeeAction } from "../services/employee-actions";
import type { Employee } from "../types";

export function EmployeeList({ employees }: { employees: Employee[] }) { if (!employees.length) return <EmptyState icon={Users} title="No employees yet" description="Add the ranch staff records needed for daily operations. Login access remains separate." href="/dashboard/employees/new" action="Add employee" />; return <div className="overflow-hidden rounded-2xl border bg-card"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-b bg-muted/40 text-left text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-5 py-3">Employee</th><th className="px-5 py-3">Position</th><th className="px-5 py-3">Contact</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y">{employees.map((employee) => <tr key={employee.id} className="hover:bg-muted/20"><td className="px-5 py-4 font-medium">{employee.first_name} {employee.last_name}{employee.nickname && <span className="block text-xs font-normal text-muted-foreground">“{employee.nickname}”</span>}</td><td className="px-5 py-4 text-muted-foreground">{employee.position || "—"}</td><td className="px-5 py-4 text-muted-foreground">{employee.email || employee.phone || "—"}</td><td className="px-5 py-4"><Badge className={employee.employment_status === "active" ? "bg-primary/10 text-primary" : ""}>{employee.employment_status}</Badge></td><td className="px-5 py-4"><div className="flex justify-end gap-1"><Button asChild variant="ghost" size="icon" aria-label="Edit employee"><Link href={`/dashboard/employees/${employee.id}/edit`}><Pencil /></Link></Button>{employee.employment_status === "active" && <form action={archiveEmployeeAction.bind(null, employee.id)}><Button variant="ghost" size="icon" aria-label="Archive employee"><Archive /></Button></form>}</div></td></tr>)}</tbody></table></div></div>; }
