"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { archiveHorse, createHorse, updateHorse, type HorseInput } from "./horse-service";
import type { HorseFormState, HorseStatus } from "../types";
function parse(formData: FormData): { input?: HorseInput; state?: HorseFormState } { const value = (key: string) => String(formData.get(key) ?? "").trim(); const name = value("name"); const rawWeight = value("weight"); const weight = rawWeight ? Number(rawWeight) : null; const fieldErrors: HorseFormState["fieldErrors"] = {}; if (!name) fieldErrors.name = "Horse name is required."; if (weight !== null && (!Number.isInteger(weight) || weight <= 0)) fieldErrors.weight = "Enter a positive whole number."; if (Object.keys(fieldErrors).length) return { state: { status: "error", fieldErrors } }; return { input: { name, barn_name: value("barnName") || null, status: (value("status") || "active") as HorseStatus, max_rider_weight_lbs: weight, temperament: value("temperament") || null, experience_level: value("experienceLevel") || null, notes: value("notes") || null } }; }
export async function createHorseAction(_state: HorseFormState, formData: FormData): Promise<HorseFormState> { const parsed = parse(formData); if (parsed.state) return parsed.state; const { error } = await createHorse(parsed.input!); if (error) return { status: "error", message: error.message }; revalidatePath("/dashboard"); redirect("/dashboard/horses"); }
export async function updateHorseAction(id: string, _state: HorseFormState, formData: FormData): Promise<HorseFormState> { const parsed = parse(formData); if (parsed.state) return parsed.state; const { error } = await updateHorse(id, parsed.input!); if (error) return { status: "error", message: error.message }; revalidatePath("/dashboard"); redirect("/dashboard/horses"); }
export async function archiveHorseAction(id: string) { const { error } = await archiveHorse(id); if (error) throw new Error("Unable to archive horse."); revalidatePath("/dashboard/horses"); revalidatePath("/dashboard"); }
